eureka:
  instance:
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
      initialization-mode: always
      sql-script-encoding: UTF-8
      password: '123456'
      url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&serverTimezone=UTC
      username: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL55Dialect
      generate-ddl: true
      hibernate:
        ddl-auto: update
      show-sql: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ecommercespring
          uri: lb://ECOMMERCESPRING
          predicates:
            - Path=/USUARIO/**
        - id: shopping-cart
          uri: lb://SHOPPING-CART
          predicates:
            - Path=/cart/**

